/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/low-poly-f1-car.glb --transform --types 
Files: ./public/low-poly-f1-car.glb [897.22KB] > /home/utelagazas/Code/Repos/hu-more-bot/low-poly-f1-car-transformed.glb [48.8KB] (95%)
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import colors from '../colors'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube002_1: THREE.Mesh
    Cube002_2: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshPhysicalMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial005: THREE.MeshStandardMaterial
  }
}

export const CarModel = forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/3dFiles/low-poly-f1-car-transformed.glb') as GLTFResult

  materials.PaletteMaterial001.color = new THREE.Color(colors.primary300.hex)
  materials.PaletteMaterial002.color = new THREE.Color(colors.secondary300.hex)
  materials.PaletteMaterial003.color = new THREE.Color(colors.tertiary300.hex)
  materials.PaletteMaterial004.color = new THREE.Color(colors.warning300.hex)
  materials.PaletteMaterial005.color = new THREE.Color(colors.primary300.hex)


  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.PaletteMaterial001} position={[-1.843, 1.745, 0]} scale={[0.257, 0.027, 1.507]} />
      <group position={[5.697, 2.828, 0]} scale={[0.371, 0.018, 0.961]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.PaletteMaterial002}/>
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.PaletteMaterial003} />
      </group>
      <group position={[-1.221, 2.314, -0.037]} rotation={[0, Math.PI / 2, 0]} scale={[0.09, 0.09, 0.031]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials.PaletteMaterial005} />
      </group>
    </group>
  )
})

useGLTF.preload('/3dFiles/low-poly-f1-car-transformed.glb')
